export const SITE_NAME = "Reddit Client"
export const SITE_DESCRIPTION = "Esto es la descripción"
export const AUTHOR = "Rafa Canosa"
export const GITHUB_URL = "https://github.com/Rafacv23/reddit-client"
export const LINKEDIN_URL = "https://ninjapath.vercel.app/linkedin"
export const PORTFOLIO_URL = "https://www.rafacanosa.dev"
